# Generated by Django 4.2.2 on 2023-06-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('route', models.CharField(max_length=255, verbose_name='Направление')),
                ('place_departure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место выезда')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rel', to='auto.auto', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заказанный трансфер',
                'verbose_name_plural': 'Заказанные трансферы',
            },
        ),
    ]
